schema_version = "1.0.0"
id = "SHIRAKUMO_sf3_io"
name = "Shirakumo SF3 IO"
version = "1.1.0"
tagline = "Export/Import support for Simple File Format Family (SF3) files"
maintainer = "Yukari Hafner"
type = "add-on"
tags = ["Import-Export"]
blender_version_min = "4.2.0"
license = ["SPDX:GPL-3.0-or-later","SPDX:Zlib"]
website = "https://github.com/Shirakumo/blender-addons/"
copyright = ["Yukari Hafner"]

[permissions]
files = "Import/export SF3 from/to disk"
